#!/bin/sh

ENV=prod
docker rm -f cucumber-test
docker rmi -f cucumber/cucumber
docker build -t cucumber/cucumber .
docker run -e ENV=${ENV} --name cucumber-test cucumber/cucumber $@
docker rm -f cucumber-test
docker rmi -f cucumber/cucumber
